### ISSUE TITLE
Check texts

### ISSUE THREAD

**Issue by linda-90** [teamforus/manuals#10]
Text on pages:

- [ ] https://help.forus.io/nijmegen/aanbieder/me/, Inloggen en hoe werkt het aanmelden
- [ ] https://help.forus.io/nijmegen/gemeente/me/, Me voor gemeente?
- [ ] https://help.forus.io/nijmegen/gemeente/fonds/, Fonds toevoegen??
- [ ] https://help.forus.io/nijmegen/gemeente/aanvragers/, Let op melding verschillende medewerkers

**Comment by GerbenBosschieter** [comment]
We gaan een helpcentrum opzetten. Wordt niet meer gewerkt aan help.forus.io
