### ISSUE TITLE
Merge menu on the left with menu on the right

### ISSUE THREAD

**Issue by linda-90** [teamforus/manuals#22]
<img width="243" alt="main menu" src="https://user-images.githubusercontent.com/36952230/54438308-b8751e00-4736-11e9-87ba-bf9354be1308.png">

<img width="231" alt="submenu" src="https://user-images.githubusercontent.com/36952230/54438309-b8751e00-4736-11e9-893e-27fa0839ead8.png">

Merge menu on the left with menu on the right

**Comment by GerbenBosschieter** [comment]
Er zal niet meer gewerkt worden aan help.forus.io . We gaan een helpcentrum opzetten.
