### ISSUE TITLE
Fix manual index

### ISSUE THREAD

**Issue by linda-90** [teamforus/manuals#7]
<img width="242" alt="manual-inhoudsopgave" src="https://user-images.githubusercontent.com/36952230/52478476-c36fe800-2ba5-11e9-8c76-fe2a4c874781.png">

De tekst achter bullet points onder Inhoudsopgave komen onder de bullet point te staan als de tekst te lang is. @GerbenBosschieter kun je dit fixen? 🐿

**Comment by GerbenBosschieter** [comment]
done
